# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lmarie <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/02/12 15:49:21 by lmarie            #+#    #+#              #
#    Updated: 2020/02/12 15:49:23 by lmarie           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

HEAD = *gch

all:
	gcc -Wextra -Werror -Wall -o $(NAME) *.c

clean:
	/bin/rm -f $(HEAD)
fclean: clean
	/bin/rm -f $(NAME) 